apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-lab-api-config
  namespace: devops-lab
  labels:
    app.kubernetes.io/name: devops-lab-api
    app.kubernetes.io/part-of: devops-lab
data:
  APP_VERSION: "0.2.0"
  APP_MESSAGE: "Hello from Kubernetes ConfigMap"
